# Generated by Django 3.2.6 on 2022-10-08 07:38

import apps.home.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название бота')),
                ('token', models.CharField(max_length=300, verbose_name='Телеграм Токен')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_type', models.CharField(choices=[('Группа', 'Группа'), ('Канал', 'Канал')], max_length=20, null=True, verbose_name='Тип Чата')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('ref', models.CharField(max_length=200, null=True, unique=True, validators=[apps.home.validators.validate_contains_https], verbose_name='Ссылка на чат')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название поста')),
                ('post_type', models.CharField(choices=[('Пост', 'Пост'), ('Опрос', 'Опрос')], max_length=20, null=True, verbose_name='Тип поста')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео')),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ')),
                ('text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Текст')),
                ('schedule', models.DateTimeField(blank=True, null=True, verbose_name='Расписание')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Активно')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bot', verbose_name='Бот')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Медиа файл')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название кнопки')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'ordering': ['id'],
            },
        ),
    ]
