# Generated by Django 3.2.6 on 2022-10-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221009_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('photos', models.ImageField(upload_to='', verbose_name='Фото')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['id'],
            },
        ),
    ]
