# Generated by Django 3.2.6 on 2022-10-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221009_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSchedule',
            fields=[
                ('schedule', models.DateTimeField(blank=True, null=True, verbose_name='Расписание')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['id'],
            },
        ),
    ]
