# Generated by Django 3.2.6 on 2022-10-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221019_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
