# Generated by Django 3.2.6 on 2022-10-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221020_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('video', models.FileField(upload_to='', verbose_name='Видео Запись')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Видео Запись',
                'verbose_name_plural': 'Видео Записи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostMusic',
            fields=[
                ('music', models.FileField(upload_to='', verbose_name='Музыкальный Трек')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Муз Трек',
                'verbose_name_plural': 'Муз Треки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('document', models.FileField(upload_to='', verbose_name='Документ')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['id'],
            },
        ),
    ]
