# Generated by Django 3.2.6 on 2022-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20221025_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='title',
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Название канала'),
        ),
    ]
