# Generated by Django 3.2.6 on 2022-11-03 12:59

import apps.home.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221025_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[apps.home.validators.validate_post_name], verbose_name='Название вашего бота'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=300, verbose_name='Бот Токен'),
        ),
        migrations.CreateModel(
            name='PostReference',
            fields=[
                ('reference', models.FileField(upload_to='', verbose_name='Ссылка')),
                ('text', models.FileField(upload_to='', verbose_name='Текст внутри ссылки')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['id'],
            },
        ),
    ]
