# Generated by Django 3.2.6 on 2022-11-03 22:30

import apps.home.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221103_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='postreference',
            name='reference',
            field=models.CharField(max_length=300, null=True, validators=[apps.home.validators.post_ref_validator], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='postreference',
            name='text',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст внутри ссылки'),
        ),
    ]
