# Generated by Django 3.2.6 on 2022-11-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221103_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphoto',
            name='photos',
        ),
        migrations.AddField(
            model_name='postphoto',
            name='photo_1',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postphoto',
            name='photo_2',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postphoto',
            name='photo_3',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postphoto',
            name='photo_4',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postphoto',
            name='photo_5',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
