# Generated by Django 3.2.6 on 2022-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221104_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 5'),
        ),
    ]
