# Generated by Django 3.2.6 on 2022-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20221106_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Музыкальный Трек'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео Запись'),
        ),
    ]
