# Generated by Django 3.2.6 on 2022-11-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20221107_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на изображение канала'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название канала'),
        ),
    ]
