# Generated by Django 3.2.6 on 2022-11-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20221108_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='subscribers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во подписчиков'),
        ),
    ]
