# Generated by Django 3.2.6 on 2022-11-08 20:30

import apps.home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20221108_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Назавание бота'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ref',
            field=models.CharField(default='', max_length=100, validators=[apps.home.validators.validate_post_name], verbose_name='Ссылка на бота'),
            preserve_default=False,
        ),
    ]
