# Generated by Django 3.2.6 on 2022-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20221108_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='negative_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество отписавшихся за сутки'),
        ),
        migrations.AddField(
            model_name='chat',
            name='positive_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество подписавшихся за сутки'),
        ),
    ]
