# Generated by Django 3.2.6 on 2022-11-12 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_auto_20221111_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Ссылка на изображение канала'),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_sent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Отправлено всего постов')),
                ('send_errors', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ошибок отправки постов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
