# Generated by Django 3.2.6 on 2022-11-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20221112_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('text', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Текст')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['id'],
            },
        ),
    ]
