# Generated by Django 3.2.6 on 2022-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20221112_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Текст'),
        ),
    ]
