# Generated by Django 3.2.6 on 2022-11-12 20:26

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_template_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='_text_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='text',
            field=markitup.fields.MarkupField(default='', no_rendered_field=True),
            preserve_default=False,
        ),
    ]
