# Generated by Django 3.2.6 on 2022-11-12 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_userstatus_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Название шаблона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='exp_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 12, 21, 8, 28, 40844), null=True, verbose_name='Оплачено по:'),
        ),
    ]
