# Generated by Django 3.2.6 on 2022-11-15 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20221112_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='postschedule',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='exp_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 15, 13, 36, 0, 665654), null=True, verbose_name='Оплачено по:'),
        ),
    ]
