# Generated by Django 3.2.6 on 2022-11-24 13:51

import apps.home.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0032_auto_20221115_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='ID чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='fri_stat_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статистика подписчиков 5'),
        ),
        migrations.AddField(
            model_name='chat',
            name='mon_stat_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статистика подписчиков 1'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sat_stat_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статистика подписчиков 6'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sun_stat_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статистика подписчиков 7'),
        ),
        migrations.AddField(
            model_name='chat',
            name='thu_stat_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статистика подписчиков 4'),
        ),
        migrations.AddField(
            model_name='chat',
            name='tue_stat_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статистика подписчиков 2'),
        ),
        migrations.AddField(
            model_name='chat',
            name='wed_stat_subs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Статистика подписчиков 3'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на изображение канала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='music',
            field=models.FileField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Музыкальный Трек'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_5',
            field=models.ImageField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Пост', 'Пост'), ('Опрос', 'Опрос')], default='Пост', max_length=20, null=True, verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=4000, null=True, validators=[apps.home.validators.post_ref_validator], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_text',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Текст внутри ссылки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, max_length=4000, null=True, upload_to='', verbose_name='Видео Запись'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='exp_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Оплачено по:'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст уведомления')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомление',
                'ordering': ['-id'],
            },
        ),
    ]
