# Generated by Django 3.2.6 on 2022-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20221128_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='main_theme',
            field=models.CharField(blank=True, choices=[('Светлая', 'white-content'), ('Темная', '')], default=None, max_length=100, verbose_name='Тема Оформления'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='primary_color',
            field=models.CharField(blank=True, choices=[('Розовый', 'primary'), ('Синий', 'blue'), ('Оранжевый', 'orange'), ('Красный', 'red'), ('Зеленый', 'green')], default=None, max_length=100, verbose_name='Основной цвет'),
        ),
    ]
