# Generated by Django 3.2.6 on 2022-11-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20221128_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='_text_rendered',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='main_theme',
            field=models.CharField(blank=True, choices=[('white-content', 'Светлая'), ('', 'Темная')], default=None, max_length=100, verbose_name='Тема Оформления'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='primary_color',
            field=models.CharField(blank=True, choices=[('primary', 'Розовый'), ('blue', 'Синий'), ('orange', 'Оранжевый'), ('red', 'Красный'), ('green', 'Зеленый')], default=None, max_length=100, verbose_name='Основной цвет'),
        ),
    ]
