# Generated by Django 3.2.6 on 2022-11-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20221130_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='tz',
            field=models.CharField(blank=True, choices=[('+4', 'Москва'), ('+4', 'СПб'), ('+6', 'Екатеринбург')], default='Москва', max_length=100, verbose_name='Город'),
        ),
    ]
