# Generated by Django 3.2.6 on 2022-11-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_userstatus_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='main_theme',
            field=models.CharField(blank=True, choices=[('white-content', 'Светлая'), ('', 'Темная')], default='Темная', max_length=100, verbose_name='Тема Оформления'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='primary_color',
            field=models.CharField(blank=True, choices=[('primary', 'Розовый'), ('blue', 'Синий'), ('orange', 'Оранжевый'), ('red', 'Красный'), ('green', 'Зеленый')], default='Розовый', max_length=100, verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='tz',
            field=models.CharField(blank=True, choices=[('+4 Москва', 'Москва'), ('+4 СПб', 'СПб'), ('+6 Екатеринбург', 'Екатеринбург')], default='Москва', max_length=100, verbose_name='Город'),
        ),
    ]
