# Generated by Django 3.2.6 on 2024-07-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20221130_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postschedule',
            name='post',
        ),
        migrations.AddField(
            model_name='postschedule',
            name='post',
            field=models.ManyToManyField(null=True, to='home.Post', verbose_name='Пост'),
        ),
    ]
