# Generated by Django 3.2.6 on 2024-07-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20240718_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postschedule',
            name='post',
        ),
        migrations.AddField(
            model_name='postschedule',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post', verbose_name='Пост'),
        ),
    ]
