# Generated by Django 3.2.6 on 2024-07-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('id_account', models.IntegerField(primary_key=True, serialize=False, verbose_name='Account ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('api_id', models.IntegerField(blank=True, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(blank=True, max_length=100, null=True, verbose_name='API HASH')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон')),
                ('sms_code', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='SMS код')),
                ('signed_in', models.BooleanField(blank=True, default=False, verbose_name='Активирован')),
                ('status', models.BooleanField(default=True, verbose_name='Состояние')),
                ('report', models.TextField(blank=True, max_length=1000000, null=True, verbose_name='Отчёт о состоянии')),
                ('session', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Сессия')),
                ('session_for_chat', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Сессия для чатов')),
                ('session_for_lk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Сессия для лс')),
                ('common_text', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Текст Рассылки')),
                ('auto_answering_text', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Текст автоответчика')),
                ('is_auto_answering_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Автоответчик вкл/выкл')),
                ('is_spam_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Спам вкл/выкл')),
                ('is_spam_lk_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Спам по ЛС вкл/выкл')),
                ('delay', models.IntegerField(blank=True, default=0, null=True, verbose_name='Задержка отправки сообщения (в минутах)')),
                ('master_to_forward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кому пересылать сообщения')),
                ('account_enabled', models.BooleanField(blank=True, default=True, null=True, verbose_name='Задействован в чатах')),
            ],
            options={
                'verbose_name': 'Спам Аккаунт',
                'verbose_name_plural': 'Спам Аккаунты',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000, verbose_name='Bot Token (‼️ не трогать ‼️)')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка на бота (‼️ не трогать ‼️)')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Бот',
            },
        ),
        migrations.CreateModel(
            name='ChannelToSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Канал для подписки',
                'verbose_name_plural': 'Каналы для подписки',
                'db_table': 'channel_to_subscribe',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('дубай обмен', 'дубай обмен'), ('работа', 'работа'), ('crypto', 'crypto'), ('пхукет', 'пхукет'), ('оаэ', 'оаэ')], default='дубай обмен', max_length=1024, verbose_name='Категория')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название чата')),
                ('subscribers', models.IntegerField(blank=True, default=0, null=True, verbose_name='Подписчиков')),
                ('username', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Ссылка или Юзернейм')),
                ('text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст для чата')),
                ('delay', models.IntegerField(blank=True, default=0, null=True, verbose_name='Задержка (мин)')),
                ('is_emoji_allowed', models.BooleanField(blank=True, default=True, null=True, verbose_name='Emoji')),
                ('is_del_mes_available', models.BooleanField(blank=True, default=True, null=True, verbose_name='Del msg')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Чат активен')),
                ('comment', models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='Комментарий')),
                ('worked_out', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отработан')),
                ('is_user_banned', models.ManyToManyField(blank=True, null=True, to='spamer.Account', verbose_name='Бан')),
            ],
            options={
                'verbose_name': 'Группа для Спама',
                'verbose_name_plural': 'Группы для Спама',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ChatMaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Chat Id')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название чата')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='#')),
            ],
            options={
                'verbose_name': 'Чат с мастер аккаунтом',
                'verbose_name_plural': 'Чаты с мастер аккаунтом',
                'db_table': 'chatmaster',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User_id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('next_time_contact', models.DateTimeField(blank=True, null=True, verbose_name='Время следующего контакта')),
                ('exchange_time', models.DateTimeField(blank=True, null=True, verbose_name='Когда поменял')),
                ('exchange_value', models.TextField(blank=True, max_length=100, null=True, verbose_name='Сколько поменял')),
                ('is_spam_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Включён в рассылку')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 1')),
                ('price_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 2')),
                ('price_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 3')),
                ('price_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 4')),
                ('forward_lk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пересыл в ЛС')),
                ('general_text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Общий Текст')),
                ('general_auto_answering', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Общий автоответчик')),
                ('general_delay', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая задержка отправки сообщения (в минутах)')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
        migrations.CreateModel(
            name='MasterAccount',
            fields=[
                ('id_account', models.IntegerField(primary_key=True, serialize=False, verbose_name='Account ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('api_id', models.IntegerField(blank=True, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(blank=True, max_length=100, null=True, verbose_name='API HASH')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone')),
                ('status', models.BooleanField(default=True, verbose_name='Состояние')),
                ('report', models.TextField(blank=True, max_length=1000000, null=True, verbose_name='Отчёт о состоянии')),
                ('session', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сессия')),
                ('is_master', models.BooleanField(blank=True, default=False, null=True, verbose_name='Мастер')),
                ('is_duplicate', models.BooleanField(blank=True, default=False, null=True, verbose_name='Дубликат')),
            ],
            options={
                'verbose_name': 'Мастер аккаунт',
                'verbose_name_plural': 'Мастер Аккаунты',
                'db_table': 'masteraccount',
            },
        ),
        migrations.CreateModel(
            name='TGAdmin',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'Админ',
                'verbose_name_plural': 'Админы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='ID сообщения')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Удалено из группы')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spamer.account', verbose_name='Аккаунт')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spamer.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='GeneralLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(blank=True, choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warning', 'Warning'), ('Fatal', 'Fatal')], max_length=50, null=True, verbose_name='Уровень логгирования')),
                ('message', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spamer.account', verbose_name='Аккаунт')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spamer.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Лог общий',
                'verbose_name_plural': 'Логи общие',
                'db_table': 'commonlogging',
            },
        ),
        migrations.CreateModel(
            name='AccountLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(blank=True, choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warning', 'Warning'), ('Fatal', 'Fatal')], max_length=50, null=True, verbose_name='Уровень логгирования')),
                ('message', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spamer.account', verbose_name='Аккаунт')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spamer.chat', verbose_name='Чат')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spamer.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Лог аккаунта',
                'verbose_name_plural': 'Логи аккаунтов',
                'db_table': 'accountlogging',
            },
        ),
    ]
