# Generated by Django 3.2.6 on 2024-07-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamer', '0003_chat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='category',
        ),
    ]
