# Generated by Django 3.2.6 on 2024-07-14 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spamer', '0004_remove_chat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltosubscribe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spamchannel', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
