# Generated by Django 3.2.6 on 2024-07-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamer', '0005_channeltosubscribe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='exchange_time',
        ),
        migrations.RemoveField(
            model_name='client',
            name='exchange_value',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_spam_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='next_time_contact',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='price_4',
        ),
    ]
