# Generated by Django 3.2.6 on 2024-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamer', '0007_auto_20240715_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
