# Generated by Django 3.2.6 on 2024-07-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamer', '0008_account_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='chat',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
