# Generated by Django 3.2.6 on 2024-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamer', '0009_auto_20240715_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='data_image',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Data Image'),
        ),
    ]
