# Generated by Django 3.2.6 on 2024-07-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamer', '0010_chat_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='session',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Сессия'),
        ),
    ]
